### PR TITLE
fix: tabnapping protection

### LINKED ISSUE #592: Tabnapping protection
We need to ensure that all of the external links from the interface do not allow for malicious links to be linked to to tabnap. 
```
In order to fix this issue you can simply add noreferrer and noopener values to the rel attribute on the link.

    <a href="https://www.google.com/" target="_blank" rel="noopener noreferrer">External link</a>
noopener
rel="noopener" prevents a new page from being able to access the window.opener property, which will stop things like the new page redirecting to a malicious URL.

noreferrer
rel="noreferrer" has the same effect as rel="noopener" but also prevents the Referer header from being sent to the new page.
```

### PR DESCRIPTION
**Pull request by levalleux-ludo**
fix #592 
- URL is sanitize before setting the "`href`" field. Applied to:
    - socialMediaLinks
    - additionalFooterLinks
    - openseaLinkToOriginalMainnetCollection
    - seller contactLinks email (only used for Dispute Resolver module)
    - seller lensUrl
    - openseaLinkToOriginalMainnetCollection (in case of Token-gated offer and commitProxyAddress is used)
    - SuccessTransactionToast.url, as a precaution, as this component is used in many different contexts
- ensure the options `rel="noopener noreferrer"` are set. Applied to:
    - socialMediaLinks
    - additionalFooterLinks
    - seller lensUrl
    - openseaLinkToOriginalMainnetCollection (in case of Token-gated offer and commitProxyAddress is used)
    - SuccessTransactionToast.url, as a precaution, as this component is used in many different contexts

Can be tested with the following URL:
- http://localhost:3333/#/?isCustomStoreFront=true&socialMediaLinks=[{"value"%3A"facebook"%2C"url"%3A"javascript:alert(1)"}]
- http://localhost:3333/#/?isCustomStoreFront=true&additionalFooterLinks=[{%22label%22%3A%22xxx%22%2C%22value%22%3A%22javascript:alert(1)%22}]
- http://localhost:3333/#/products/ede57c-6ad-621-0d1c-434ef1525a2a?isCustomStoreFront=true&commitProxyAddress=0x0000000000000000000000000000000000000000&openseaLinkToOriginalMainnetCollection=javascript:alert(1) (product UUID `ede57c-6ad-621-0d1c-434ef1525a2a` only valid on staging environment)

### CODE REVIEW

File: src/components/disputeResolver/ManageDisputes/DisputesTable.tsx [hunk 1]
```diff
@@ -175,7 +176,7 @@ export default function DisputesTable({ disputes }: Props) {
                     whiteSpace: "pre"
                   }}
                   onClick={() => {
-                    copyToClipboard(emailAddress).then(() => {
+                    copyToClipboard(sanitizeUrl(emailAddress)).then(() => {
```
Comment (albertfolch-redeemeum) [inline src/components/disputeResolver/ManageDisputes/DisputesTable.tsx:179]: does this work or break the emailAddress that's copied even if it's a valid email address? @levalleux-ludo

Comment (levalleux-ludo) [reply src/components/disputeResolver/ManageDisputes/DisputesTable.tsx:179]: Checked.
Before:
image

After:
image

**Review by albertfolch-redeemeum — APPROVED** [review]
